### ISSUE TITLE
it.isDirectory is unresolved

### ISSUE THREAD

**Issue by nomaed** [wadejensen/kotlin-fat-jar-example#1]
I saw this example in several places but it doesn't work for me.

![screen shot 2019-02-08 at 19 09 13](https://user-images.githubusercontent.com/9551921/52493827-1a40e600-2bd5-11e9-9f54-d9ba994cdeed.png)

I am not creating a new task, just adding fat jar to current:

```kotlin
tasks.withType<Jar> {
    manifest {
        attributes["MainClass"] = "com.nomaed.demo.Application"
    }
    from(configurations.runtime.map({ if (it.isDirectory) it else zipTree(it) }))
}
```

**Comment by wadejensen** [comment]
I'm not a gradle expert I'm afraid, I'm not familiar with what you're doing because you're using a different task syntax and potentially the context of the DSL is different. I just threw this up so I could copy-paste exactly what I had once I got it working, I hate shaving yaks when starting a new project.

Best of luck.

**Comment by nomaed** [comment]
I figured that `configuration.runtime` should be of the same type, and `.map()` would have the same argument types.

So I take it that your version still works for you with current versions of Gradle (5.2)?

**Comment by aflatt** [comment]
@nomaed I had the same issue, try the following instead (add the call to `.get()`) and it should fix it:
`from(configurations.runtime.get().map({ if (it.isDirectory) it else zipTree(it) }))`

See this for more info: 
https://stackoverflow.com/questions/41794914/how-to-create-the-fat-jar-with-gradle-kotlin-script#comment94561276_43998029

**Comment by nomaed** [comment]
Thank you! I will try this.

**Comment by breandan** [comment]
Note that you also need to exclude `**.kotlin_metadata` files from the JAR due to [this issue](https://youtrack.jetbrains.com/issue/KT-25709).
